CK/Controllers/StockController.cs
using CK.Model;
using CK.Models;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using OfficeOpenXml;
using System.Diagnostics;
using System.Globalization;
using Newtonsoft.Json;
using OfficeOpenXml.Style;
using Polly;
using System;
using ClosedXML.Excel;
using System.Drawing;
using Microsoft.CodeAnalysis.Elfie.Model.Structures;
using System.Linq;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using System.Text;
using Microsoft.Data.SqlClient;
using DocumentFormat.OpenXml.Features;
using static System.Runtime.InteropServices.JavaScript.JSType;
using Microsoft.IdentityModel.Tokens;
using System.Data;
using DocumentFormat.OpenXml.InkML;
using System.Security.Cryptography;
using System.Windows.Forms;
using System.Security.Cryptography.X509Certificates;
namespace CK.Controllers
{
	[Authorize]
	public class StockController : Controller
	{
        AxdbContext Axdb = new AxdbContext();
        DataCenterContext db = new DataCenterContext();
        CkproUsersContext db2 = new CkproUsersContext();
        CkhelperdbContext db3 = new CkhelperdbContext();
        DataCenterPrevYrsContext db4 = new DataCenterPrevYrsContext();
        private readonly ILogger<StockController> _logger;
		public StockController(ILogger<StockController> logger)
		{
			_logger = logger;
		}
		bool exported = false;
		[HttpGet]
		public IActionResult Index()
		{
			DataCenterContext db = new DataCenterContext();
			CkproUsersContext db2 = new CkproUsersContext();
			CkhelperdbContext db3 = new CkhelperdbContext();
			AxdbContext Axdb = new AxdbContext();
			DataCenterPrevYrsContext db4 = new DataCenterPrevYrsContext();
			db.Database.SetCommandTimeout(7200);// Set the timeout in seconds
												//Store List Text=StoreName , Value = StoreId
			var username = HttpContext.Session.GetString("Username");
			var Role = HttpContext.Session.GetString("Role");
			ViewBag.Username = username;
			ViewBag.Role = Role;

			if (username is null)
			{
				return RedirectToAction("Store", "Home");
			}
			bool isDmanager = db2.RptUsers.Any(s => s.Dmanager == username);
			bool isFmanager = db2.RptUsers.Any(s => s.Fmanager == username);
			bool isUsername = db2.RptUsers.Any(s => s.Username == username && (s.Storenumber != null || s.Storenumber != " "));

			IQueryable<Storeuser> query;
			if (isDmanager || isUsername || isFmanager)
			{
				// If the username matches either the Dmanager or the Username, filter the stores accordingly
				query = db2.Storeusers
					.Where(s => s.Dmanager == username || s.Username == username || s.Fmanager == username);
			}
			else
			{
				// If neither condition is met, display all stores
				query = db2.Storeusers;
			}
			ViewBag.VBStore = query
	.GroupBy(m => m.Name)
	.Select(group => new { Store = group.First().Storenumber + ":" + group.First().RmsstoNumber, Name = group.Key })
	.OrderBy(m => m.Name)
	.ToList();
			ViewBag.VBDepartment = Axdb.Ecorescategories
												 .GroupBy(m => m.Name)
												 .Select(group => new { Code = group.First().Code, Name = group.Key })
												 .OrderBy(m => m.Name)
												 .ToList();

			//Supplier List Text=SupplierName , Value = Code 
			ViewBag.VBSupplier = db.Suppliers
											 .GroupBy(m => m.SupplierName)
												 .Select(group => new { Code = group.First().Code, SupplierName = group.Key })
												 .OrderBy(m => m.SupplierName)
												 .ToList();

			ViewBag.VBItemBarcode = db.Items.Select(m => new { m.Id, m.ItemLookupCode }).Distinct();
			ViewBag.VBStoreFranchise = db.Stores
				 .Where(m => m.Franchise != null)
				 .Select(m => m.Franchise)
				 .Distinct()
				 .ToList();
			return View();
		}
        [HttpPost]
        public IActionResult Index(SalesParameters Parobj)
        {
            DataCenterContext db = new DataCenterContext();
            CkproUsersContext db2 = new CkproUsersContext();
            CkhelperdbContext db3 = new CkhelperdbContext();
            DataCenterPrevYrsContext db4 = new DataCenterPrevYrsContext();
            db.Database.SetCommandTimeout(7200);// Set the timeout in seconds
            db3.Database.SetCommandTimeout(7200);// Set the timeout in seconds
            db4.Database.SetCommandTimeout(7200);// Set the timeout in seconds
            var username = HttpContext.Session.GetString("Username");
            var Role = HttpContext.Session.GetString("Role");
            ViewBag.Username = username;
            ViewBag.Role = Role;

            ViewBag.VBStore = db2.Storeusers
                    .Where(s => s.Dmanager == username || s.Username == username)
                .GroupBy(m => m.Name)
                .Select(group => new { Store = group.First().Storenumber + ":" + group.First().RmsstoNumber, Name = group.Key })//group.First().StoreIdD + ":" +
                .OrderBy(m => m.Name)
                .ToList();
            ViewBag.VBDepartment = db.Departments
                                                 .GroupBy(m => m.Name)
                                                 .Select(group => new { Code = group.First().Code, Name = group.Key })
                                                 .OrderBy(m => m.Name)
                                                 .ToList();

            //Supplier List Text=SupplierName , Value = Code 
            ViewBag.VBSupplier = db.Suppliers
                                             .GroupBy(m => m.SupplierName)
                                                 .Select(group => new { Code = group.First().Code, SupplierName = group.Key })
                                                 .OrderBy(m => m.SupplierName)
                                                 .ToList();

            ViewBag.VBItemBarcode = db.Items.Select(m => new { m.Id, m.ItemLookupCode }).Distinct();
            ViewBag.VBStoreFranchise = db.Stores
                 .Where(m => m.Franchise != null)
                 .Select(m => m.Franchise)
                 .Distinct()
                 .ToList();
            // Dynamic GroupBy based on selected values
            IQueryable<dynamic> reportData1;
            string[] storeVal = Parobj.Store.Split(':');
            string connectionStringAXDB = string.Format("Server=192.168.1.210;User ID=sa;Password=P@ssw0rd;Database=AXDB;Connect Timeout=7200;Encrypt=False;TrustServerCertificate=True;ApplicationIntent=ReadWrite;MultiSubnetFailover=False;");
            string connectionString = string.Format("Server=192.168.1.156;User ID=sa;Password=P@ssw0rd;Database=DATA_CENTER;Connect Timeout=7200;Encrypt=False;TrustServerCertificate=True;ApplicationIntent=ReadWrite;MultiSubnetFailover=False;");
            string connectionString2 = string.Format("Server=192.168.1.156;User ID=sa;Password=P@ssw0rd;Database=DATA_CENTER_Prev_Yrs;Connect Timeout=7200;Encrypt=False;TrustServerCertificate=True;ApplicationIntent=ReadWrite;MultiSubnetFailover=False;");
            string serverIp = GetServerIpFromDatabase();
            // Step 2: Format the connection string dynamically
            //string connectionString = FormatConnectionString(serverIp);
            // Call the ExportToExcel method

            if ((Parobj.RMS && Parobj.TMT == false) || (Parobj.RMS && storeVal[0] == "RMS"))
            {
                return ExportToExcel(connectionString, Parobj);
            }
            else if (Parobj.RMS == false && Parobj.TMT || (storeVal.Length > 1 && storeVal[1] == "Dy"))
            {
                return ExportToExcel(connectionStringAXDB, Parobj);
            }
            else if (Parobj.RMS && Parobj.TMT)
            {
                return ExportToExcel(connectionString, Parobj);
            }
            else if (Parobj.DBbefore)
            {
                return ExportToExcel(connectionString2, Parobj);
            }
            // if Not RMS or TMT
            else
            {
                return View();
            }
            ViewBag.Data = reportData1;
            Parobj.exportAfterClick = true;
            if (Parobj.exportAfterClick == false)
            {
                return View();
            }

            else
            {
                return View();
            }

        }
        [HttpGet]
        public IActionResult StockFromBranch()
        {
            db.Database.SetCommandTimeout(7200);// Set the timeout in seconds
            IQueryable<RptSale> RptSales = db.RptSales;
            IQueryable<RptSalesAxt> RptSalesAxts = db.RptSalesAxts;
            IQueryable<RptSales2> RptSales2s = db4.RptSales2s;
            IQueryable<RptSalesAll> RptSalesAlls = db.RptSalesAlls;
            //Store List Text=StoreName , Value = StoreId
            var username = HttpContext.Session.GetString("Username");
            var Role = HttpContext.Session.GetString("Role");
            var Server = HttpContext.Session.GetString("Server");
            ViewBag.Username = username;
            ViewBag.Role = Role; ViewBag.Username = username;
            bool isDmanager = db2.RptUsers.Any(s => s.Dmanager == username);
            bool isUsername = db2.RptUsers.Any(s => s.Username == username && (s.Storenumber != null || s.Storenumber != " "));
            IQueryable<Storeuser> query;
            if (isDmanager || isUsername)
            {
				ViewBag.IsUsername = "true";
                // If the username matches either the Dmanager or the Username, filter the stores accordingly
                query = db2.Storeusers
                    .Where(s => s.Dmanager == username || s.Username == username);
            }
            else
            {
                // If neither condition is met, display all stores
                query = db2.Storeusers;
            }
            ViewBag.VBStore = query
    .GroupBy(m => m.Name)
    .Select(group => new { Store = group.First().Storenumber + ":" + group.First().RmsstoNumber, Name = group.Key })
    .OrderBy(m => m.Name)
    .ToList();

CK/Views/Stock/StockFromBranch - Copy.cshtml
@*  @model CK.Models.SalesParameters;
 *@
 @model List<CK.Models.RptSale>
 
 @addTagHelper*, Microsoft.AspNetCore.Mvc.TagHelpers
@{
    var role = ViewBag.Role;
    var username = ViewBag.IsUsername;
    if (role == "Manager")
    {
        Layout = "~/Views/Shared/_Layout.cshtml";
    }
    else if (role == "Sales_NewS_Stock_Tender")
    {
        Layout = "~/Views/Shared/_LayoutS_S_T.cshtml";
    }
    else if (role == "Sales_NewS_Tender")
    {
        Layout = "~/Views/Shared/_LayoutS_T.cshtml";
    }
    else if (role == "TerrManager")
    {
        Layout = "~/Views/Shared/_LayoutS_S_F.cshtml";
    }
    else if (role == "Sales_NewS_Stock")
    {
        Layout = "~/Views/Shared/_LayoutS_S.cshtml";
    }
    else if (role == "Sales_NewS" || role == "FoodManager")
    {
        Layout = "~/Views/Shared/_LayoutS.cshtml";
    }
    else
    {
        Layout = "~/Views/Shared/_Layout2.cshtml";
    }
}
<!Doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Circle K</title>
    <script>
        var preventBack = @Html.Raw(Json.Serialize(ViewData["PreventBack"] ?? false));

        if (preventBack) {
            window.history.pushState(null, "", location.href);
            window.onpopstate = function () {
                window.history.pushState(null, "", location.href);
            };
        }
    </script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>

</head>


<body class="hold-transition @* sidebar-mini layout-fixed *@">
    @*     @ViewBag.Username
    *@
    <div class="preloader">
        <div class="sk-spinner sk-spinner-wave">
            <div class="sk-rect1"></div>
            <div class="sk-rect2"></div>
            <div class="sk-rect3"></div>
            <div class="sk-rect4"></div>
            <div class="sk-rect5"></div>
        </div>
    </div>
    <div class="wrapper" style="margin-left:0;">
        <div class="content-wrapper" style="margin-left:0;">
            <div class="container-fluid">
                <div class="row mb-2">

                    <div class="col-sm-6">
                    </div>
                </div>
            </div>
            <form id="exportForm" asp-controller="Stock" asp-action="StockFromBranch" method="post">
                <section class="content">
                    <div class="container-fluid">
                        <div class="row">
                            <section class="col-lg-7 ">


                                    @* <div class="col-md-3">
                                    <li class="Displayli" style="display:none">
                                                        <select class="FilterSelect form-control" name="Parobj.Store" asp-items="@(new SelectList(ViewBag.VBStore,"Store","Name"))">

                                                            <option value="0">All Stores</option>
                                                        </select>
                                                    </li>
                                                    <input type="hidden" id="selectedStores" name="Parobj.Store" value="Store" />
                                                    <li class="Displayliselect">
                                                        <label>Department:</label>
                                                        <br>
                                                        <select class="FilterSelect form-control" name="Parobj.Department" asp-items="@(new SelectList(ViewBag.VBDepartment,"Code","Name"))">
                                                            <option value="0">All Department</option>
                                                        </select>
                                                    </li>
                                            </div> *@
                            </section>
                            @if (Model != null && Model.Any())
                            {
                                <table id="example" class="table">
                                    <thead>
                                        <tr>
                                            <th>From</th>
                                            <th>Quantity</th>
                                            <th>Item</th>
 
                                        </tr>
                                    </thead>
                                    <tbody>
                                        @foreach (var item in Model)
                                        {
                                            <tr>
                                                <td>
                                                    <img src="/images/bg-01.jpg" width="200px" />
                                                </td>
                                                <td>@item.StoreName</td>
                                                <td>@item.DpName</td>
                                            </tr>
                                        }
                                    </tbody>
                                </table>
                            }

                            @*                                 <img id="loader-gif" src="/images/loading-23.gif" alt="" />
                            *@@*                                 <img id="loader-gif2" src="/images/200w.gif" alt="" />
                            *@
                        </div>Elapsed Time :
                        <div id="stopwatch" style="display:inline-block">00:00:00</div><br />
                        <button type="submit" id="exportButton" class="btn btn-primary">Execute</button>
                    </div>
                </section>
            </form>
        </div>
    </div>
       <script src="/js/main.js"></script>
    <script src="/plugins/jquery/jquery.min.js"></script>
    <script src="/dist/js/adminlte.js"></script>

        <script>
        let startTime, elapsed = 0;
        let checkStatusInterval; // Define checkStatusInterval in a scope accessible to both functions
        let stopwatchDisplay = document.getElementById('stopwatch');
        let exportButton = document.getElementById('exportButton');
        let exportForm = document.getElementById('exportForm');
        let intervalId = null;

        function startStopwatch() {
            console.log('Starting stopwatch...');
            startTime = Date.now();
            intervalId = setInterval(() => {
                elapsed = Date.now() - startTime;
                stopwatchDisplay.textContent = formatElapsedTime(elapsed);
            }, 100);
            console.log('Stopwatch started with interval ID:', intervalId);
        }

        function stopStopwatch() {
            if (intervalId) {
                clearInterval(intervalId);
                intervalId = null;
            }
        }

        function formatElapsedTime(elapsed) {
            let hours = Math.floor(elapsed / 3600000);
            let minutes = Math.floor((elapsed % 3600000) / 60000);
            let seconds = ((elapsed % 60000) / 1000).toFixed(0);
            return `${pad(hours)}:${pad(minutes)}:${pad(seconds)}`;
        }

        function pad(number) {
            return number < 10 ? '0' + number : number;
        }

        exportButton.addEventListener('click', function (event) {
            event.preventDefault();
            exportButton.disabled = true;

            // Get the date input fields
            let startDate = document.getElementById('startDate'); 
            let endDate = document.getElementById('endDate');
            let DBbefore = document.getElementById('DBbefore');
            let TMT = document.getElementById('TMT');
            let RMS = document.getElementById('RMS');
            let checkboxes = [
                { id: 'VFranchise', name: 'Parobj.VFranchise' },
                { id: 'VStoreId', name: 'Parobj.VStoreId' },
                { id: 'VStoreName', name: 'Parobj.VStoreName' },
                { id: 'VSupplierId', name: 'Parobj.VSupplierId' },
                { id: 'VSupplierName', name: 'Parobj.VSupplierName' },
                { id: 'VDpId', name: 'Parobj.VDpId' },
                { id: 'VDepartment', name: 'Parobj.VDepartment' },
                { id: 'VItemLookupCode', name: 'Parobj.VItemLookupCode' },
                { id: 'VItemName', name: 'Parobj.VItemName' },
                { id: 'VQty', name: 'Parobj.VQty' },
            ];

            // Check if any of the checkboxes are not checked
           // let unchecked = checkboxes.every(checkbox => !document.getElementById(checkbox.id).checked);
            // Check if the date fields are filled out
            // If the fields are filled out, start the stopwatch and submit the form
            startStopwatch();
            submitExportForm(); // Submit the export form
        });

     // Event listener for the cancel export button
     cancelExportButton.addEventListener('click', function (event) {
         event.preventDefault();
         cancelExport(); // Call the cancelExport function
     });

     // Function to handle export submission
     function submitExportForm() {
            exportForm.submit(); // Submit the export form
           
                checkExportStatus(); // Check export status immediately after submission
         return;
                // Set up an interval to check export status periodically
                checkStatusInterval = setInterval(checkExportStatus, 1000);

     }

        function checkExportStatus() {
            $.ajax({
                url: '/Stock/CheckExportStatus',
                type: 'GET',
                success: function (status) {
                    console.log(status);
                    if (status === 'unknown1') {
                        alert('An error occurred during the export process. Please try again.');
                        clearInterval(checkStatusInterval); // Clear the interval on error
                    } else if (status === 'complete') {
                        stopStopwatch();
                        exportButton.disabled = false;
                        // Optionally, clear the interval to stop checking the status if the process is complete
                        clearInterval(checkStatusInterval);
                    } else {
                        setTimeout(checkExportStatus, 1000);
                    }
                },
                error: function () {
                    alert('An error occurred during the export process. Please try again.');
                    exportButton.disabled = false;
                    clearInterval(checkStatusInterval); // Clear the interval on error
                }
            });
        }
    </script>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
</body>
</html>

CK/Views/Stock/StockFromBranch.cshtml
@model CK.Models.SalesParameters;
@addTagHelper*, Microsoft.AspNetCore.Mvc.TagHelpers
@{
    var role = ViewBag.Role;
    var username = ViewBag.IsUsername;
    Layout = "~/Views/Shared/_Layout.cshtml";
    // if (role == "Manager")
    // {
    //     Layout = "~/Views/Shared/_Layout.cshtml";
    // }
    // else if (role == "Sales_NewS_Stock_Tender")
    // {
    //     Layout = "~/Views/Shared/_LayoutS_S_T.cshtml";
    // }
    // else if (role == "Sales_NewS_Tender")
    // {
    //     Layout = "~/Views/Shared/_LayoutS_T.cshtml";
    // }
    // else if (role == "TerrManager")
    // {
    //     Layout = "~/Views/Shared/_LayoutS_S_F.cshtml";
    // }
    // else if (role == "Sales_NewS_Stock")
    // {
    //     Layout = "~/Views/Shared/_LayoutS_S.cshtml";
    // }
    // else if (role == "Sales_NewS" || role == "FoodManager")
    // {
    //     Layout = "~/Views/Shared/_LayoutS.cshtml";
    // }
    // else
    // {
    //     Layout = "~/Views/Shared/_Layout2.cshtml";
    // }
}
<!Doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.13.2/themes/base/jquery-ui.css" rel="stylesheet">
    <link href="https://cdn.datatables.net/1.13.6/css/dataTables.jqueryui.css" rel="stylesheet">
    <link href="https://cdn.datatables.net/buttons/2.4.1/css/buttons.jqueryui.css" rel="stylesheet">
    <link href="https://cdn.datatables.net/rowreorder/1.4.1/css/rowReorder.jqueryui.css" rel="stylesheet">
    <link href="https://cdn.datatables.net/searchpanes/2.2.0/css/searchPanes.jqueryui.css" rel="stylesheet">
    <script src="https://code.jquery.com/jquery-3.7.0.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.13.2/jquery-ui.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.10.1/jszip.js"></script>
    <script src="https://cdn.datatables.net/1.13.6/js/jquery.dataTables.js"></script>
    <script src="https://cdn.datatables.net/1.13.6/js/dataTables.jqueryui.js"></script>
    <script src="https://cdn.datatables.net/buttons/2.4.1/js/dataTables.buttons.js"></script>
    <script src="https://cdn.datatables.net/buttons/2.4.1/js/buttons.jqueryui.js"></script>
    <script src="https://cdn.datatables.net/buttons/2.4.1/js/buttons.colVis.js"></script>
    <script src="https://cdn.datatables.net/buttons/2.4.1/js/buttons.html5.js"></script>
    <script src="https://cdn.datatables.net/buttons/2.4.1/js/buttons.print.js"></script>
    <script src="https://cdn.datatables.net/rowreorder/1.4.1/js/dataTables.rowReorder.js"></script>
    <script src="https://cdn.datatables.net/searchpanes/2.2.0/js/dataTables.searchPanes.js"></script>
    <script src="https://cdn.datatables.net/searchpanes/2.2.0/js/searchPanes.jqueryui.js"></script>
    <script type="text/javascript" src="/js/site.js"></script>
    <script>
        var preventBack = @Html.Raw(Json.Serialize(ViewData["PreventBack"] ?? false));

        if (preventBack) {
            window.history.pushState(null, "", location.href);
            window.onpopstate = function () {
                window.history.pushState(null, "", location.href);
            };
        }
    </script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <style>
        .main-footer
        {
            position:relative !important;
        }
    </style>
</head>


<body class="hold-transition @* sidebar-mini layout-fixed *@">
    @*     @ViewBag.Username
    *@
    <div class="preloader">
        <div class="sk-spinner sk-spinner-wave">
            <div class="sk-rect1"></div>
            <div class="sk-rect2"></div>
            <div class="sk-rect3"></div>
            <div class="sk-rect4"></div>
            <div class="sk-rect5"></div>
        </div>
    </div>
    <div class="wrapper" style="margin-left:0;">
        <div class="content-wrapper" style="margin-left:0;">
            <div class="container-fluid">
                <div class="row mb-2">

                    <div class="col-sm-6">
                    </div>
                </div>
            </div>
            <form id="exportForm" asp-controller="Stock" asp-action="StockFromBranch" method="post">
                <section class="content">
                    <div class="container-fluid">
                        <div class="row">
                            <section class="col-lg-7 ">


                                    <div class="col-md-3">
                                    <li class="Displayli" style="display:none">
                                                        <select class="FilterSelect form-control" name="Parobj.Store" asp-items="@(new SelectList(ViewBag.VBStore,"Store","Name"))">
                                                            <option value="0">All Stores</option>
                                                        </select>
                                                    </li>
                                                    <input type="hidden" id="selectedStores" name="Parobj.Store" value="Store" />
                                                    <li class="Displayliselect">
                                                        <label>Department:</label>
                                                        <br>
                                        <select class="FilterSelect form-control" name="Parobj.Department" asp-items="@(new SelectList(ViewBag.VBDepartment,"Code","Name"))">
                                            <option value="0">All Department</option>
                                        </select>
                                                    </li>
                                                    @*removed disabled *@
                                            </div>
                            </section>
                            @*                                 <img id="loader-gif" src="/images/loading-23.gif" alt="" />
                            *@@*                                 <img id="loader-gif2" src="/images/200w.gif" alt="" />
                            *@
                        </div>
@*                         <div id="stopwatch" style="display:inline-block">00:00:00</div><br />
 *@                        <button type="submit" id="exportButton" class="btn btn-primary">Execute</button>
                    </div>
                </section>
            </form>
            <div id="salesReportTableWrapper">
                @if (ViewBag.Data != null)
                {
                    <table id="salesReportTable" class="table">
                        <thead>
                            <tr>
                                <th>StoreName</th>
                                <th>Itemlookupcode</th>
                                <th>ItemName</th>
                                 <th>Balance</th>
                                 <th >Quantity</th>
                             </tr>
                        </thead>
                        <tbody>
                            @foreach (var dr in ViewBag.Data)
                            {
                                <tr>
                                    <td>@dr.StoreName</td>
                                    <td>@dr.ItemLookupCode</td>
                                    <td>@dr.ItemName</td>
                                    <td><input type="number" value="0" /></td>
                                    <td >@dr.Qty</td>
                                 </tr>
                            }
                        </tbody>
                    </table>
                }
            </div>
        </div>
    </div>

    <script>
        var ExportFormat = {

            format: {
                body: function (data, row, column, node) {
                    //check if type is input using jquery
                    return $('input', node).length ?
                        $(node).find('input').val() :
                        data;

                }
            }

        };


        var table = $('#salesReportTable').DataTable({
            pageLength: 20, // Set the number of rows per page
            dom: 'Bfrtip',
            buttons: [{
                extend: 'excelHtml5', exportOptions: ExportFormat
            }]



        });
       
    </script>
</body>
</html>