CK/Controllers/BranchesController.cs
using CK.Models;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using System.Security.Claims;
using Microsoft.AspNetCore.Cryptography.KeyDerivation;
using System.Security.Cryptography;
using System.Text;
using DocumentFormat.OpenXml.Spreadsheet;
using CK.Model;
using DocumentFormat.OpenXml.Wordprocessing;
namespace CK.Controllers
{
    public class BranchesController : Controller
    {
        AxdbContext Axdb = new AxdbContext();
        DataCenterContext db = new DataCenterContext();
        CkproUsersContext db2 = new CkproUsersContext();
        CkhelperdbContext db3 = new CkhelperdbContext();
        DataCenterPrevYrsContext db4 = new DataCenterPrevYrsContext();
        private readonly ILogger<BranchesController> _logger;
        private readonly CkproUsersContext _dbContext;
        private static readonly List<RptUser3> Users = new List<RptUser3>();
        public BranchesController(ILogger<BranchesController> logger, CkproUsersContext dbContext)
        {
            _logger = logger;
            _dbContext = dbContext;
        }
 
        public string encrypt(string clearText)
        {
            string EncryptionKey = "MAKV2SPBNI99212";
            byte[] clearBytes = Encoding.Unicode.GetBytes(clearText);
            using (Aes encryptor = Aes.Create())
            {
                Rfc2898DeriveBytes pdb = new Rfc2898DeriveBytes(EncryptionKey, new byte[] { 0x49, 0x76, 0x61, 0x6e, 0x20, 0x4d, 0x65, 0x64, 0x76, 0x65, 0x64, 0x65, 0x76 });
                encryptor.Key = pdb.GetBytes(32);
                encryptor.IV = pdb.GetBytes(16);
                using (MemoryStream ms = new MemoryStream())
                {
                    using (CryptoStream cs = new CryptoStream(ms, encryptor.CreateEncryptor(), CryptoStreamMode.Write))
                    {
                        cs.Write(clearBytes, 0, clearBytes.Length);
                        cs.Close();
                    }
                    clearText = Convert.ToBase64String(ms.ToArray());
                }
            }
            return clearText;
        }
        public string Decrypt(string clearText)
        {
            string DecryptionKey = "MAKV2SPBNI99212";
            byte[] clearBytes = Convert.FromBase64String(clearText);
            using (Aes decryptor = Aes.Create())
            {
                Rfc2898DeriveBytes pdb = new Rfc2898DeriveBytes(DecryptionKey, new byte[] { 0x49, 0x76, 0x61, 0x6e, 0x20, 0x4d, 0x65, 0x64, 0x76, 0x65, 0x64, 0x65, 0x76 });
                decryptor.Key = pdb.GetBytes(32);
                decryptor.IV = pdb.GetBytes(16);
                using (MemoryStream ms = new MemoryStream())
                {
                    using (CryptoStream cs = new CryptoStream(ms, decryptor.CreateDecryptor(), CryptoStreamMode.Write))
                    {
                        cs.Write(clearBytes, 0, clearBytes.Length);
                        cs.Close();
                    }
                    clearText = Encoding.Unicode.GetString(ms.ToArray());
                }
            }
            return clearText;
        }

        [HttpGet]
        //[ValidateAntiForgeryToken]
        public IActionResult CreateStore()
        {
            var user = new User();
            ViewBag.MaxId = _dbContext.Storeusers.Max(x => x.Id+1);
            var username = HttpContext.Session.GetString("Username");
            var Role = HttpContext.Session.GetString("Role");
            ViewBag.Username = username;
            ViewBag.Role = Role;
            return View();
        }
        [HttpPost]
        //[ValidateAntiForgeryToken]
        public async Task<IActionResult> CreateStore([Bind("Inventlocation,Storenumber,Username,Password,Name,Server,RmsstoNumber,Id,Email,Dbase,PriceCategory,Franchise,Company,Zkip,StartDate,ArabicN,District,Dmanager,Fmanager")] Storeuser store)
        {
            // Encrypt the password before saving
            store.Inventlocation ??= "Null";
            store.Storenumber ??= "Null";
            store.RmsstoNumber ??= "Null";
            store.ArabicN ??= "Null";
            store.Company ??= "Null";
            store.StartDate ??= "Null";
            store.Dbase ??= "Null";
            store.DecryptedPassword ??= "Null";
            store.District ??= "Null";
            store.Dmanager ??= "UnKnown";
            store.Fmanager ??= "UnKnown";
            store.Email ??= "Null";
            store.Franchise??= "Null";
            store.Name ??= "Null";
            store.PriceCategory ??= "Null";
            store.Server ??= "Null";
            store.Zkip ??= "Null";
            store.Username ??= "Null";
            store.Password = encrypt(store.Password);

            _dbContext.Add(store);
            await _dbContext.SaveChangesAsync();
            return RedirectToAction("DisplayStores");
        }
        public IActionResult DisplayStores()
        {
            var username = HttpContext.Session.GetString("Username");
            var Role = HttpContext.Session.GetString("Role");
            ViewBag.Username = username;
            ViewBag.Role = Role;
            var stores = _dbContext.Storeusers.OrderByDescending(x => x.Id).ToList();
            return View(stores);
        }

        [HttpGet]
        public async Task<IActionResult> EditStore(int? id)
        {
            var username = HttpContext.Session.GetString("Username");
            var Role = HttpContext.Session.GetString("Role");
            ViewBag.Username = username;
            ViewBag.Role = Role;
            var stores = await _dbContext.Storeusers.FindAsync(id);
            //if Password Encrypted Algorithm is not 64 i will display this password as it -Ahmed Hosny
            try
            {
                stores.Password = Decrypt(stores.Password);
            }
            catch (Exception ex)
            {
                stores.Password = stores.Password;
            }
            //stores.Password = Decrypt(stores.Password);
            return View(stores);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> EditStore(int id, [Bind("Inventlocation,Storenumber,Username,Password,Name,Server,RmsstoNumber,Id,Email,Dbase,PriceCategory,Franchise,Company,Zkip,StartDate,ArabicN,District,Dmanager,Fmanager")] Storeuser store)
        {

            store.Inventlocation ??= "Null";
            store.Storenumber ??= "Null";
            store.RmsstoNumber ??= "Null";
            store.ArabicN ??= "Null";
            store.Company ??= "Null";
            store.StartDate ??= "Null";
            store.Dbase ??= "Null";
            store.DecryptedPassword ??= "Null";
            store.District ??= "Null";
            store.Dmanager ??= "UnKnown";
            store.Fmanager ??= "UnKnown";
            store.Email ??= "Null";
            store.Franchise ??= "Null";
            store.Name ??= "Null";
            store.PriceCategory ??= "Null";
            store.Server ??= "Null";
            store.Zkip ??= "Null";
            store.Username ??= "Null";
            store.Password = encrypt(store.Password);
            _dbContext.Update(store);
            await _dbContext.SaveChangesAsync();
            return RedirectToAction("DisplayStores");
        }

        [HttpPost]
        public IActionResult DeleteStore(int? id)
        {
            // Retrieve the user details from the database based on the username
            var store = _dbContext.Storeusers.FirstOrDefault(u => u.Id == id);
            if (store == null)
            {
                return NotFound(); // Return a 404 Not Found if user is not found
            }

            // Remove the user from the database
            _dbContext.Storeusers.Remove(store);
            _dbContext.SaveChanges();

            // Redirect to the display users page after the deletion is successful
            return RedirectToAction("DisplayStores");
        }
        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }

}

CK/Views/Branches/CreateStore.cshtml
@model CK.Models.Storeuser
@{
    var role = ViewBag.Role;
    if (role == "Manager")
    {
        Layout = "~/Views/Shared/_Layout.cshtml";
    }
    else if (role == "Sales_NewS_Stock_Tender")
    {
        Layout = "~/Views/Shared/_LayoutS_S_T.cshtml";
    }
    else if (role == "Sales_NewS_Tender")
    {
        Layout = "~/Views/Shared/_LayoutS_T.cshtml";
    }
    else if (role == "TerrManager")
    {
        Layout = "~/Views/Shared/_LayoutS_S_F.cshtml";
    }
    else if (role == "Sales_NewS_Stock")
    {
        Layout = "~/Views/Shared/_LayoutS_S.cshtml";
    }
    else if (role == "Sales_NewS" || role == "FoodManager")
    {
        Layout = "~/Views/Shared/_LayoutS.cshtml";
    }
    else
    {
        Layout = null;
    }
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Form Example</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet">
    <style>
        body {
            font-family: Arial, sans-serif;
        }

        /* Form styles */
        .form-group {
            margin-bottom: 15px;
        }

        /* Button styles */
        .btn-primary {
            margin-top: 20px;
        }

        /* Responsive grid layout */

       .fileds
       {
           display:inline-block;
           margin:10px 50px;
            font-family: auto;
            font-size: 21px;
       }
       .filed label{
           padding:3%;
       }
       ul
       {
           width:1500px;
       }

        .Title {
            background-color: #b50101;
            font-family: emoji;
            font-weight: bold;
        }
    </style>
</head>
<body>
    <button class="btn btn-primary Title">Create Store</button>
<form asp-action="CreateStore" method="post" class="needs-validation" novalidate>
    <ul>
        <li class="fileds">
                <label for="Id">Id</label>
                <input type="text" style="font-weight:bold" class="form-control" id="Id" value="@ViewBag.MaxId" disabled>
        </li><br />
            <li class="fileds">
            <label asp-for="Inventlocation">Inventlocation</label>
            <input asp-for="Inventlocation" class="form-control" style="width:250px" />
        </li>
            <li class="fileds">
                <label asp-for="Storenumber">Storenumber</label>
                <input asp-for="Storenumber" class="form-control" style="width:250px" />
            </li>
            <li class="fileds">
                <label asp-for="Username">Username</label>
                <input asp-for="Username" class="form-control" style="width:250px" />
            </li>
            <li class="fileds">
                <label asp-for="Name">Name</label>
                <input asp-for="Name" class="form-control" style="width:250px" />
            </li>
            <li class="fileds">
                <label asp-for="Server">Server</label>
                <input asp-for="Server" class="form-control" style="width:250px" />
            </li>
            <li class="fileds">
                <label asp-for="RmsstoNumber">RmsstoNumber</label>
                <input asp-for="RmsstoNumber" class="form-control" style="width:250px" />
            </li>
            <li class="fileds">
                <label asp-for="Email">Email</label>
                <input asp-for="Email" class="form-control" style="width:250px" />
            </li>
            <li class="fileds">
                <label asp-for="Dbase">Dbase</label>
                <input asp-for="Dbase" class="form-control" style="width:250px" />
            </li>
            <li class="fileds">
                <label asp-for="PriceCategory">PriceCategory</label>
                <input asp-for="PriceCategory" class="form-control" style="width:250px" />
            </li>
            <li class="fileds">
                <label asp-for="Franchise">Franchise</label>
                <input asp-for="Franchise" class="form-control" style="width:250px" />
            </li>
            <li class="fileds">
                <label asp-for="Company">Company</label>
                <input asp-for="Company" class="form-control" style="width:250px" />
            </li>
            <li class="fileds">
                <label asp-for="Zkip">Zkip</label>
                <input asp-for="Zkip" class="form-control" style="width:250px" />
            </li>
            <li class="fileds">
                <label asp-for="StartDate">StartDate</label>
                <input asp-for="StartDate" class="form-control" style="width:250px" />
            </li>
            <li class="fileds">
                <label asp-for="ArabicN">ArabicN</label>
                <input asp-for="ArabicN" class="form-control" style="width:250px" />
            </li>
            <li class="fileds">
                <label asp-for="District">District</label>
                <input asp-for="District" class="form-control" style="width:250px" />
            </li>
            <li class="fileds">
                <label asp-for="Dmanager">Dmanager</label>
                <input asp-for="Dmanager" class="form-control" style="width:250px" />
            </li>
            <li class="fileds">
                <label asp-for="Fmanager">Fmanager</label>
                <input asp-for="Fmanager" class="form-control" style="width:250px" />
            </li>
            <li class="fileds">
                <label asp-for="Password">Password</label>
                <input asp-for="Password" class="form-control" style="width:250px" />
            </li>
            <li class="fileds"></li>
            <li class="fileds"></li>
        </ul>
    <button type="submit" class="btn btn-primary">Create Store</button>
        <a asp-controller="Branches" asp-action="DisplayStores" class="btn btn-primary">Display Stores</a>
</form>
</body>
</html>

CK/Views/Branches/DisplayStores.cshtml
@model List<CK.Models.Storeuser>
@{
        Layout = null;
}
<!Doctype html>
<html>
<head>
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/2.0.5/css/dataTables.dataTables.css">
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/buttons/3.0.2/css/buttons.dataTables.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="/plugins/fontawesome-free/css/all.min.css">
    <!-- Ionicons -->
    <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <!-- Tempusdominus Bootstrap 4 -->
    <link rel="stylesheet" href="/plugins/tempusdominus-bootstrap-4/css/tempusdominus-bootstrap-4.min.css">
    <!-- iCheck -->
    <link rel="stylesheet" href="/plugins/icheck-bootstrap/icheck-bootstrap.min.css">
    <!-- JQVMap -->
    <link rel="stylesheet" href="/plugins/jqvmap/jqvmap.min.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="/dist/css/adminlte.min.css">
    <!-- overlayScrollbars -->
    <link rel="stylesheet" href="/plugins/overlayScrollbars/css/OverlayScrollbars.min.css">
    <!-- Daterange picker -->
    <link rel="stylesheet" href="/plugins/daterangepicker/daterangepicker.css">
    <!-- summernote -->
    <link rel="stylesheet" href="/plugins/summernote/summernote-bs4.min.css">
    <link rel="stylesheet" href="/css/test.css" />
    <link rel="stylesheet" href="/plugins/bootstrap/date.css" />
    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/pikaday/1.8.2/css/pikaday.min.css">
    <!--for date-->
    <script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

    <script type="text/javascript" src="https://ajax.aspnetcdn.com/ajax/jQuery/jquery-1.8.3.min.js"></script>

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">

    <!-- jQuery -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"></script>

    <!-- Bootstrap JS -->
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>

    <!-- Datepicker JS -->
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.6.4/js/bootstrap-datepicker.js"></script>
    @*     <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
    *@

    <script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>
    <!-- Add Bootstrap CSS (you may have this already) -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <style>
        .dt-search {
            float: right;
        }

        .Title {
            background-color: #b50101;
            font-family: emoji;
            font-weight: bold;
        }
    </style>
</head>
<body>
    <button class="btn btn-primary Title">Stores</button>
    <a asp-controller="Branches" asp-action="CreateStore" class="btn btn-primary">Create Store</a>
    <a asp-controller="Home" asp-action="Home" class="btn btn-primary">Home</a>
    <table id="example" class="table">
        <thead>
            <tr>
                <th>Edit</th>
                <th>Delete</th>
                <th>Inventlocation</th>
                <th>Dmanager</th>
                <th>Fmanager</th>
                <th>Storenumber</th>
                <th>Name</th>
                <th>Server</th>
                <th>RmsstoNumber</th>
                <th>Id</th>
                <th>Email</th>
                <th>Dbase</th>
                <th>PriceCategory</th>
                <th>Franchise</th>
                <th>Company</th>
                <th>Zkip</th>
                <th>StartDate</th>
                <th>ArabicN</th>
                <th>District</th>
                <th>Password</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var store in Model)
            {
                <tr>
                    <td>
                        <form asp-controller="Branches" asp-action="EditStore" method="get">
                            <input type="hidden" name="Id" value="@store.Id" />
                            <button type="submit" class="btn btn-primary">Edit</button>
                        </form>
                    </td>
                    <td>
                        <form asp-controller="Branches" asp-action="DeleteStore" method="post" onsubmit="return confirm('Are you sure you want to delete this user?');">
                            <input type="hidden" name="Id" value="@store.Id" />
                            <button type="submit" class="btn btn-danger">Delete</button>
                        </form>
                    </td>
                    <td>@store.Inventlocation</td>
                    <td>@store.Dmanager</td>
                    <td>@store.Fmanager</td>
                    <td>@store.Storenumber</td>
                    <td>@store.Name</td>
                    <td>@store.Server</td>
                    <td>@store.RmsstoNumber</td>
                    <td>@store.Id</td>
                    <td>@store.Email</td>
                    <td>@store.Dbase</td>
                    <td>@store.PriceCategory</td>
                    <td>@store.Franchise</td>
                    <td>@store.Company</td>
                    <td>@store.Zkip</td>
                    <td>@store.StartDate</td>
                    <td>@store.ArabicN</td>
                    <td>@store.District</td>
                    <td>@store.Password</td>
                </tr>
            }
        </tbody>
    </table>

    <script src="https://cdn.datatables.net/1.10.25/js/jquery.dataTables.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.7.1.js"></script>
    <script src="https://cdn.datatables.net/2.0.5/js/dataTables.js"></script>
    <script src="https://cdn.datatables.net/buttons/3.0.2/js/dataTables.buttons.js"></script>
    <script src="https://cdn.datatables.net/buttons/3.0.2/js/buttons.dataTables.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.10.1/jszip.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.2.7/pdfmake.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.2.7/vfs_fonts.js"></script>
    <script src="https://cdn.datatables.net/buttons/3.0.2/js/buttons.html5.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/3.0.2/js/buttons.print.min.js"></script>
    <script>
        $(document).ready(function () {
            var table = $('#example').DataTable({
                pageLength: 20, // Set the number of rows per page
                lengthChange: true, // Enable the length change input control
                dom: 'Blfrtip', // Define the placement of the buttons
                buttons: [
                    'pdf', 'excel' // Specify the buttons
                ]
            });

            // Move the buttons to the top of the table
            new $.fn.dataTable.Buttons(table, {
                buttons: [
                    'pdf'
                ]
            }).container().appendTo($('#example_wrapper').find('.col-sm-6:eq(0)'));
        });

    </script>
</body>
</html>

CK/Views/Branches/EditStore.cshtml
@model CK.Models.Storeuser
@{
    var role = ViewBag.Role;
    if (role == "Manager")
    {
        Layout = "~/Views/Shared/_Layout.cshtml";
    }
    else if (role == "Sales_NewS_Stock_Tender")
    {
        Layout = "~/Views/Shared/_LayoutS_S_T.cshtml";
    }
    else if (role == "Sales_NewS_Tender")
    {
        Layout = "~/Views/Shared/_LayoutS_T.cshtml";
    }
    else if (role == "TerrManager")
    {
        Layout = "~/Views/Shared/_LayoutS_S_F.cshtml";
    }
    else if (role == "Sales_NewS_Stock")
    {
        Layout = "~/Views/Shared/_LayoutS_S.cshtml";
    }
    else if (role == "Sales_NewS" || role == "FoodManager")
    {
        Layout = "~/Views/Shared/_LayoutS.cshtml";
    }
    else
    {
        Layout = null;
    }
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Edit Store</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet">
    <style>
        body {
            font-family: Arial, sans-serif;
        }

        /* Form styles */
        .form-group {
            margin-bottom: 15px;
        }

        /* Button styles */
        .btn-primary {
            margin-top: 20px;
        }

        /* Responsive grid layout */

       .fileds
       {
           display:inline-block;
           margin:10px 50px;
            font-family: auto;
            font-size: 21px;
       }
       .filed label{
           padding:3%;
       }
       ul
       {
           width:1500px;
       }
       .Title
       {
            background-color: #b50101;
            font-family: emoji;
            font-weight: bold;
       }
    </style>
</head>
<body>
    <button class="btn btn-primary Title">Edit Store</button>

    <form asp-action="EditStore" method="post" >
    <ul>
            <input type="hidden" asp-for="Id" />
            <li class="fileds">
            <label asp-for="Inventlocation">Inventlocation</label>
            <input asp-for="Inventlocation" class="form-control" style="width:250px" />
        </li>
            <li class="fileds">
                <label asp-for="Storenumber">Storenumber</label>
                <input asp-for="Storenumber" class="form-control" style="width:250px" />
            </li>
            <li class="fileds">
                <label asp-for="Username">Username</label>
                <input asp-for="Username" class="form-control" style="width:250px" />
            </li>
            <li class="fileds">
                <label asp-for="Name">Name</label>
                <input asp-for="Name" class="form-control" style="width:250px" />
            </li>
            <li class="fileds">
                <label asp-for="Server">Server</label>
                <input asp-for="Server" class="form-control" style="width:250px" />
            </li>
            <li class="fileds">
                <label asp-for="RmsstoNumber">RmsstoNumber</label>
                <input asp-for="RmsstoNumber" class="form-control" style="width:250px" />
            </li>
            <li class="fileds">
                <label asp-for="Email">Email</label>
                <input asp-for="Email" class="form-control" style="width:250px" />
            </li>
            <li class="fileds">
                <label asp-for="Dbase">Dbase</label>
                <input asp-for="Dbase" class="form-control" style="width:250px" />
            </li>
            <li class="fileds">
                <label asp-for="PriceCategory">PriceCategory</label>
                <input asp-for="PriceCategory" class="form-control" style="width:250px" />
            </li>
            <li class="fileds">
                <label asp-for="Franchise">Franchise</label>
                <input asp-for="Franchise" class="form-control" style="width:250px" />
            </li>
            <li class="fileds">
                <label asp-for="Company">Company</label>
                <input asp-for="Company" class="form-control" style="width:250px" />
            </li>
            <li class="fileds">
                <label asp-for="Zkip">Zkip</label>
                <input asp-for="Zkip" class="form-control" style="width:250px" />
            </li>
            <li class="fileds">
                <label asp-for="StartDate">StartDate</label>
                <input asp-for="StartDate" class="form-control" style="width:250px" />
            </li>
            <li class="fileds">
                <label asp-for="ArabicN">ArabicN</label>
                <input asp-for="ArabicN" class="form-control" style="width:250px" />
            </li>
            <li class="fileds">
                <label asp-for="District">District</label>
                <input asp-for="District" class="form-control" style="width:250px" />
            </li>
            <li class="fileds">
                <label asp-for="Dmanager">Dmanager</label>
                <input asp-for="Dmanager" class="form-control" style="width:250px" />
            </li>
            <li class="fileds">
                <label asp-for="Fmanager">Fmanager</label>
                <input asp-for="Fmanager" class="form-control" style="width:250px" />
            </li>
            <li class="fileds">
                <label asp-for="Password">Password</label>
                <input asp-for="Password" class="form-control" style="width:250px" />
            </li>
            <li class="fileds"></li>
            <li class="fileds"></li>
        </ul>
        <button type="submit" class="btn btn-primary">Save Changes</button>
</form>
</body>
</html>